HoundsRace.Web/Controllers/RaceEventsController.cs
using HoundsRace.Web.CustomFilters;
using HoundsRace.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HoundsRace.Web.Controllers
{
    public class RaceEventsController : Controller
    {

        private IRaceEventsRepository repository;

        public RaceEventsController()
            : this(new RaceEventRepository())
        {
        }

        public RaceEventsController(IRaceEventsRepository repository)
        {
            this.repository = repository;
        }

        public ActionResult List()
        {
            var raceEventsModel = this.repository.GetAllRaceEvents();

            return View(raceEventsModel);
        }

        [AjaxRequestsOnly]
        public ActionResult Details(int id)
        {
            var raceEventDetailedModel = this.repository.GetRaceEventById(id);

            if (raceEventDetailedModel == null)
            {
                RedirectToAction("List");
            }

            return PartialView("_RaceEventDetails", raceEventDetailedModel.DogEntries);
        }
    }
}

HoundsRace.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Hounds Race Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Hounds Race", "List", "RaceEvents", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Hounds Race Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquery.unobtrusive-ajax")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>